spring.application.name: user-profile-service
spring.kafka.bootstrap-servers: localhost:9092
spring.aerospike.hosts: localhost:3000
spring.data.aerospike.namespace: user-profile

user-properties:
  - name: age
    topic: user-registered
  - name: country
    topic: user-registered
    path: userCountry
  - name: purchaseCount
    topic: event-purchase

kafka-topics:
  - topic: user-registered
  - topic: event-purchase
    user-id-source: uid

router.topic:
  name: router
  partitions: 24
  concurrency: 6


cache.configuration:
  number-of-partitions: 6
  max-number-of-items: 100000
  expire-after-write: 1m

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

