spring.application.name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


user-profile-service.partitions: 24

spring:
  cloud:
    gateway:
      routes:
        - id: user-profile-service
          uri: no://op
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: UserProfileRoutingFilter
server:
  port: 8090
